server:
  port: 0
spring:
  application:
    name: swipe-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: swipes
      port: 27017
      host: swipes-database

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
