server:
  port: 0
spring:
  application:
    name: user-profile-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: users
    password: password
    url: jdbc:postgresql://users-database:5432/ms_users
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "currency.converter.application@gmail.com"
#    password: "{cipher}AQC8x7RLChhu6m34MUS8am+y2/2JnmFfgl2bPK9Me1IQQMu+oXpDUGYFUrbSlNP+5uY0/BLaLhe7yBrDpnCYKbWfO393+GoPfYzJZg7DQAtH7sX36fF31aJslD9vemjvJuEfLSpsxXa11v2pudS/BhXA6v8eYByzZXxT1Ycf2cmTBW6mOoCq4oLANSBcRiWwAsaULhgT/W1O679yH6ApdFCqkwCUT0eQ5WDr08VirUvkehT13qZlYLLIewNiU5Yq4nBJKQbGXnp76kjdofFE0AG2EboDPfOziRGUfLUKW3xQaEoB1qLTEA1mXZOesYU3gyG6gFGJ2iSlcPXan/EO9j5RcyPpcPg4MGR/sir2bQMo/J4hqIitz3h4hy4zYCIXr3UBmiXhMMZHHEm1YjDe9srj"
    password: "pfflgjzzkihpksck"
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          ssl:
            trust: "smtp.gmail.com"
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    subject: "Invitation link"

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}